# -*- coding: utf-8 -*-
"""src/sector_classification_pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tywWNxfmWVQ5wYxN1NcxCj5nbw5c8BfB
"""

import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.pipeline import Pipeline
from sklearn.model_selection import StratifiedKFold, cross_val_predict
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, f1_score, classification_report, confusion_matrix


# =========================
# Paths
# =========================
DATA_PATH = "/content/sector_training_data.csv"
OUTPUT_DIR = "outputs"
os.makedirs(OUTPUT_DIR, exist_ok=True)


# =========================
# Load data
# =========================
df = pd.read_csv(DATA_PATH)

# basic cleaning
for col in ["title", "turn1", "turn2", "combined_text"]:
    if col in df.columns:
        df[col] = df[col].fillna("").astype(str)

df["sector_label"] = df["sector_label"].astype(str).str.strip()
df["confidence"] = df["confidence"].astype(str).str.strip().str.upper()

X = df["combined_text"]
y = df["sector_label"]


# =========================
# Sector distribution plot
# =========================
counts = df["sector_label"].value_counts().sort_values(ascending=True)

from matplotlib.colors import LinearSegmentedColormap
soft_green_cmap = LinearSegmentedColormap.from_list(
    "soft_green",
    ["#f3f7df", "#c7e3b5", "#6fb47b"]
)
colors = soft_green_cmap(np.linspace(0, 1, len(counts)))

fig, ax = plt.subplots(figsize=(11, 6.5))
bars = ax.barh(counts.index, counts.values, color=colors, edgecolor="none", height=0.65)

ax.set_title("Sector Label Distribution", fontsize=16, pad=14)
ax.set_xlabel("Count", fontsize=13)
ax.set_ylabel("")
ax.tick_params(axis='y', labelsize=12)
ax.tick_params(axis='x', labelsize=11)

for bar in bars:
    width = bar.get_width()
    ax.text(width + 0.8, bar.get_y() + bar.get_height()/2,
            f"{int(width)}", va="center", ha="left",
            fontsize=11, color="#2f4f2f")

ax.grid(axis="x", linestyle="--", alpha=0.25)
ax.spines["top"].set_visible(False)
ax.spines["right"].set_visible(False)
ax.spines["left"].set_visible(False)
ax.set_xlim(0, counts.max() + 10)

plt.tight_layout()
plt.savefig(os.path.join(OUTPUT_DIR, "sector_distribution.png"), dpi=300, bbox_inches="tight")
plt.close()


# =========================
# Model definitions
# =========================
sector_clf_unweighted = Pipeline([
    ("tfidf", TfidfVectorizer(
        lowercase=True,
        stop_words="english",
        ngram_range=(1, 2),
        min_df=2,
        max_df=0.95
    )),
    ("clf", LogisticRegression(
        max_iter=3000,
        class_weight="balanced"
    ))
])

sector_clf_weighted = Pipeline([
    ("tfidf", TfidfVectorizer(
        lowercase=True,
        stop_words="english",
        ngram_range=(1, 2),
        min_df=2,
        max_df=0.95
    )),
    ("clf", LogisticRegression(
        max_iter=3000,
        class_weight="balanced"
    ))
])

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)


# =========================
# Unweighted CV evaluation
# =========================
y_cv_pred_unweighted = cross_val_predict(sector_clf_unweighted, X, y, cv=cv)

acc_unweighted = accuracy_score(y, y_cv_pred_unweighted)
f1_unweighted = f1_score(y, y_cv_pred_unweighted, average="macro")

report_unweighted = classification_report(y, y_cv_pred_unweighted, output_dict=True)
report_unweighted_df = pd.DataFrame(report_unweighted).transpose()
report_unweighted_df.to_csv(os.path.join(OUTPUT_DIR, "classification_report_unweighted.csv"))

labels = sorted(df["sector_label"].unique())
cm_unweighted = confusion_matrix(y, y_cv_pred_unweighted, labels=labels)

plt.figure(figsize=(12, 8))
sns.heatmap(cm_unweighted, annot=True, fmt="d", cmap="Blues",
            xticklabels=labels, yticklabels=labels)
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("CV Confusion Matrix - Unweighted Sector Classification")
plt.xticks(rotation=45, ha="right")
plt.yticks(rotation=0)
plt.tight_layout()
plt.savefig(os.path.join(OUTPUT_DIR, "confusion_matrix_cv_unweighted.png"), dpi=300, bbox_inches="tight")
plt.close()


# =========================
# Weighted CV evaluation
# =========================
confidence_map = {
    "HIGH": 1.0,
    "MEDIUM": 0.7,
    "LOW": 0.4
}
df["sample_weight"] = df["confidence"].map(confidence_map).fillna(1.0)

X_arr = df["combined_text"].values
y_arr = df["sector_label"].values
w_arr = df["sample_weight"].values

all_true = []
all_pred = []

for train_idx, test_idx in cv.split(X_arr, y_arr):
    X_train, X_test = X_arr[train_idx], X_arr[test_idx]
    y_train, y_test = y_arr[train_idx], y_arr[test_idx]
    w_train = w_arr[train_idx]

    sector_clf_weighted.fit(X_train, y_train, clf__sample_weight=w_train)
    y_pred = sector_clf_weighted.predict(X_test)

    all_true.extend(y_test)
    all_pred.extend(y_pred)

acc_weighted = accuracy_score(all_true, all_pred)
f1_weighted = f1_score(all_true, all_pred, average="macro")

report_weighted = classification_report(all_true, all_pred, output_dict=True)
report_weighted_df = pd.DataFrame(report_weighted).transpose()
report_weighted_df.to_csv(os.path.join(OUTPUT_DIR, "classification_report_weighted.csv"))

cm_weighted = confusion_matrix(all_true, all_pred, labels=labels)

plt.figure(figsize=(12, 8))
sns.heatmap(cm_weighted, annot=True, fmt="d", cmap="Oranges",
            xticklabels=labels, yticklabels=labels)
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.title("CV Confusion Matrix - Confidence-weighted Sector Classification")
plt.xticks(rotation=45, ha="right")
plt.yticks(rotation=0)
plt.tight_layout()
plt.savefig(os.path.join(OUTPUT_DIR, "confusion_matrix_cv_weighted.png"), dpi=300, bbox_inches="tight")
plt.close()


# =========================
# Save metrics summary
# =========================
metrics_df = pd.DataFrame({
    "model": ["unweighted", "confidence_weighted"],
    "cv_accuracy": [acc_unweighted, acc_weighted],
    "cv_macro_f1": [f1_unweighted, f1_weighted]
})
metrics_df.to_csv(os.path.join(OUTPUT_DIR, "metrics_summary.csv"), index=False)


# =========================
# Final unweighted model fit on all labelled data
# =========================
final_sector_clf = Pipeline([
    ("tfidf", TfidfVectorizer(
        lowercase=True,
        stop_words="english",
        ngram_range=(1, 2),
        min_df=2,
        max_df=0.95
    )),
    ("clf", LogisticRegression(
        max_iter=3000,
        class_weight="balanced"
    ))
])

final_sector_clf.fit(X, y)


# =========================
# Top keywords from final main model
# =========================
vectorizer = final_sector_clf.named_steps["tfidf"]
clf = final_sector_clf.named_steps["clf"]

feature_names = np.array(vectorizer.get_feature_names_out())
classes = clf.classes_

with open(os.path.join(OUTPUT_DIR, "top_keywords_unweighted.txt"), "w", encoding="utf-8") as f:
    for i, label in enumerate(classes):
        top10 = np.argsort(clf.coef_[i])[-10:]
        top_words = ", ".join(feature_names[top10])
        f.write(f"Top keywords for {label}:\n{top_words}\n\n")


# =========================
# Error analysis from unweighted CV
# =========================
cv_results = df[["debate_id", "title", "turn1", "turn2", "sector_label", "confidence"]].copy()
cv_results["predicted"] = y_cv_pred_unweighted
cv_results = cv_results.rename(columns={"sector_label": "actual"})

cv_errors = cv_results[cv_results["actual"] != cv_results["predicted"]].copy()
cv_errors.to_csv(os.path.join(OUTPUT_DIR, "error_analysis_unweighted.csv"), index=False)

error_pairs = (
    cv_errors.groupby(["actual", "predicted"])
    .size()
    .reset_index(name="count")
    .sort_values("count", ascending=False)
)
error_pairs.to_csv(os.path.join(OUTPUT_DIR, "error_pairs_unweighted.csv"), index=False)

print("Done. Outputs saved in:", OUTPUT_DIR)
print(metrics_df)